name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile project
      run: mvn compile
      working-directory: JavaPathENProject8-master/TourGuide

    - name: Run unit tests (excluding performance tests)
      run: mvn test -Dtest=\!TestPerformance
      working-directory: JavaPathENProject8-master/TourGuide

    - name: Build artifact (.jar)
      run: mvn package -DskipTests
      working-directory: JavaPathENProject8-master/TourGuide
