name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install local dependencies (gpsUtil, tripPricer, rewardCentral)
      run: |
        mkdir -p ~/.m2/repository/gpsUtil/gpsUtil/1.0.0
        cp JavaPathENProject8-master/TourGuide/libs/gpsUtil-1.0.0.jar ~/.m2/repository/gpsUtil/gpsUtil/1.0.0/gpsUtil-1.0.0.jar

        mkdir -p ~/.m2/repository/tripPricer/tripPricer/1.0.0
        cp JavaPathENProject8-master/TourGuide/libs/tripPricer-1.0.0.jar ~/.m2/repository/tripPricer/tripPricer/1.0.0/tripPricer-1.0.0.jar

        mkdir -p ~/.m2/repository/rewardCentral/rewardCentral/1.0.0
        cp JavaPathENProject8-master/TourGuide/libs/rewardCentral-1.0.0.jar ~/.m2/repository/rewardCentral/rewardCentral/1.0.0/rewardCentral-1.0.0.jar

    - name: Compile TourGuide
      run: mvn compile
      working-directory: JavaPathENProject8-master/TourGuide

    - name: Run unit tests (excluding performance tests)
      run: mvn test -Dtest=\!TestPerformance
      working-directory: JavaPathENProject8-master/TourGuide

    - name: Build TourGuide jar
      run: mvn package -DskipTests
      working-directory: JavaPathENProject8-master/TourGuide
